### ISSUE TITLE
Datapackage script for Project Drawdown

### ISSUE THREAD

**Issue by sneha-sharma12** [sneha-sharma12/learning-dataset#1]
When I am using dataset from [awesome-data](https://github.com/datasets/awesome-data/issues), I want to select a Project Drawdown dataset so I can turn it into a data package with a script to automate collecting the data

## Acceptance

* [x] CSV file is created and saved
* [x] datapackage.json is created

## Tasks

* [x] Fetch data from table 
* [x] Convert data into json
* [x] Convert and save data in CSV form
* [x] Create datapackage.json

## Analysis
TODO
